name: 'Sync Camunda Milestones'
description: 'Synchronize milestones with branches in repository'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token: 
    description: 'Github Access Token'
    required: true
  webmodeler-client-id: 
    description: 'Camunda Web Modeler Client Id'
    required: true
  webmodeler-client-secret: 
    description: 'Camunda Web Modeler Client Secret'
    required: true    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
