name: 'Sync Camunda Milestones'
description: 'Synchronize milestones with branches in repository'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  githubToken: 
    description: 'Github Access Token (${{ secrets.GITHUB_TOKEN }})'
    required: true    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
